version: '3'
services:
    postgresql:
        image: postgres
        restart: always
        container_name: postgres

        ports:
            - '5432:5432'

        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: password

        volumes:
            - ./data/postgres/:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4
        restart: always
        container_name: pgadmin4

        ports:
            - '5050:80'

        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: password

        volumes:
            - ./data/pgadmin/:/var/lib/pgadmin
